#!/usr/bin/env bash

# Handle special env vars in case of Kubernetes
if [[ "${SPARK_MASTER_PORT}" =~ ^([a-zA-Z]+)(://)([-a-zA-Z0-9.]+)(:)([0-9]+) ]]
then
    echo "Extracting host and port from Kubernetes environment"
    export SPARK_MASTER_HOST="${BASH_REMATCH[3]}"
    export SPARK_MASTER_PORT="${BASH_REMATCH[5]}"
fi

export SPARK_MASTER_HOST=${SPARK_MASTER_HOST="spark-master"}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT=7077}
export SPARK_MASTER=${SPARK_MASTER="spark://$SPARK_MASTER_HOST:$SPARK_MASTER_PORT"}
export SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT=8080}

export SPARK_WORKER_CORES=${SPARK_WORKER_CORES=4}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY="8G"}
export SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT=8081}
export SPARK_LOCAL_DIRS=${SPARK_LOCAL_DIRS="/tmp/spark-local"}
export SPARK_WORKER_DIR=${SPARK_WORKER_DIR="/tmp/spark-worker"}

export SPARK_DRIVER_WEBUI_PORT=${SPARK_DRIVER_WEBUI_PORT=4040}

# Spark event log and history setting
export SPARK_HISTORY_ENABLED=${SPARK_HISTORY_ENABLED="true"}
export SPARK_HISTORY_DIR=${SPARK_HISTORY_DIR="file:///tmp/spark-history"}
export SPARK_HISTORY_CLEANER_ENABLED=${SPARK_HISTORY_CLEANER_ENABLED="true"}
export SPARK_HISTORY_WEBUI_PORT=${SPARK_HISTORY_WEBUI_PORT=18080}

# S3 properties
export S3_PROXY_HOST=${S3_PROXY_HOST}
export S3_PROXY_PORT=${S3_PROXY_PORT="-1"}
export S3_PROXY_USE_HTTPS=${S3_PROXY_USE_HTTPS="false"}
export S3_ENDPOINT=${S3_ENDPOINT}
export S3_ENDPOINT_HTTP_PORT=${S3_ENDPOINT_HTTP_PORT="80"}
export S3_ENDPOINT_HTTPS_PORT=${S3_ENDPOINT_HTTPS_PORT="443"}

export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
