export HADOOP_HOME=${HADOOP_HOME}
export SPARK_HOME=${SPARK_HOME}
export SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT}

export SPARK_WEBUI_PORT=${SPARK_WEBUI_PORT}
export SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
export SPARK_LOCAL_DIRS=${SPARK_LOCAL_DIRS}
export SPARK_WORKER_DIR=${SPARK_WORKER_DIR}

