export SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT}

export SPARK_WEBUI_PORT=${SPARK_WEBUI_PORT}
export SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
export SPARK_LOCAL_DIRS=${SPARK_LOCAL_DIRS}
export SPARK_WORKER_DIR=${SPARK_WORKER_DIR}

# S3 properties
export S3_PROXY_HOST=${S3_PROXY_HOST}
export S3_PROXY_PORT=${S3_PROXY_PORT}
export S3_PROXY_USE_HTTPS=${S3_PROXY_USE_HTTPS=false}
export S3_ENDPOINT=${S3_ENDPOINT=s3.amazonaws.com}
export S3_ENDPOINT_HTTP_PORT=${S3_ENDPOINT_HTTP_PORT=80}
export S3_ENDPOINT_HTTPS_PORT=${S3_ENDPOINT_HTTPS_PORT=443}

export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
